export const enum State {
    NOT_INITIALIZED,
    COMPUTING,
    COMPUTING_PASSIVE,
    CLEAN,
    MAYBE_DIRTY,
    DIRTY,
    PASSIVE,
    DESTROYED,
}

export const MAX_REACTION_ITERATIONS = 1000;
