name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18
        cache: 'yarn.lock'

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Run tests
      run: yarn test
  
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
